"""Document type definitions and field schemas for all 8 supported document types."""
from __future__ import annotations

DOC_TYPES: dict[str, dict] = {
    "invoice": {
        "label": "Invoice",
        "description": "Vendor invoice or bill document",
        "fields": [
            {"name": "vendor",        "label": "Vendor",         "field_type": "text"},
            {"name": "invoice_no",    "label": "Invoice #",      "field_type": "text"},
            {"name": "date",          "label": "Invoice Date",   "field_type": "date"},
            {"name": "due_date",      "label": "Due Date",       "field_type": "date"},
            {"name": "bill_to",       "label": "Bill To",        "field_type": "text"},
            {"name": "subtotal",      "label": "Subtotal",       "field_type": "currency"},
            {"name": "tax",           "label": "Tax",            "field_type": "currency"},
            {"name": "total",         "label": "Total Amount",   "field_type": "currency"},
            {"name": "payment_terms", "label": "Payment Terms",  "field_type": "text"},
        ],
    },
    "receipt": {
        "label": "Receipt",
        "description": "Purchase receipt or transaction record",
        "fields": [
            {"name": "merchant",        "label": "Merchant",        "field_type": "text"},
            {"name": "date",            "label": "Date",            "field_type": "date"},
            {"name": "items_summary",   "label": "Items Summary",   "field_type": "text"},
            {"name": "subtotal",        "label": "Subtotal",        "field_type": "currency"},
            {"name": "tax",             "label": "Tax",             "field_type": "currency"},
            {"name": "total",           "label": "Total",           "field_type": "currency"},
            {"name": "payment_method",  "label": "Payment Method",  "field_type": "text"},
        ],
    },
    "contract": {
        "label": "Contract",
        "description": "Legal contract or formal agreement",
        "fields": [
            {"name": "parties",           "label": "Parties",           "field_type": "text"},
            {"name": "contract_type",     "label": "Contract Type",     "field_type": "text"},
            {"name": "effective_date",    "label": "Effective Date",    "field_type": "date"},
            {"name": "termination_date",  "label": "End / Expiry Date", "field_type": "date"},
            {"name": "jurisdiction",      "label": "Jurisdiction",      "field_type": "text"},
            {"name": "governing_law",     "label": "Governing Law",     "field_type": "text"},
            {"name": "key_obligations",   "label": "Key Obligations",   "field_type": "text"},
        ],
    },
    "resume": {
        "label": "Resume / CV",
        "description": "Professional resume or curriculum vitae",
        "fields": [
            {"name": "name",              "label": "Full Name",              "field_type": "text"},
            {"name": "email",             "label": "Email",                  "field_type": "text"},
            {"name": "phone",             "label": "Phone",                  "field_type": "text"},
            {"name": "location",          "label": "Location",               "field_type": "text"},
            {"name": "linkedin",          "label": "LinkedIn",               "field_type": "text"},
            {"name": "github",            "label": "GitHub",                 "field_type": "text"},
            {"name": "current_title",     "label": "Current / Target Title", "field_type": "text"},
            {"name": "experience_years",  "label": "Years of Experience",    "field_type": "text"},
            {"name": "top_skills",        "label": "Top Skills",             "field_type": "text"},
            {"name": "technical_skills",  "label": "Technical Skills",       "field_type": "text"},
            {"name": "education_summary", "label": "Education",              "field_type": "text"},
            {"name": "work_experience",   "label": "Work Experience",        "field_type": "text"},
            {"name": "projects",          "label": "Projects",               "field_type": "text"},
            {"name": "certifications",    "label": "Certifications",         "field_type": "text"},
            {"name": "achievements",      "label": "Achievements / Awards",  "field_type": "text"},
            {"name": "languages",         "label": "Languages",              "field_type": "text"},
        ],
    },
    "medical_report": {
        "label": "Medical Report",
        "description": "Medical examination, lab, or diagnostic report",
        "fields": [
            {"name": "patient_name",  "label": "Patient Name",       "field_type": "text"},
            {"name": "patient_dob",   "label": "Date of Birth",      "field_type": "date"},
            {"name": "report_date",   "label": "Report Date",        "field_type": "date"},
            {"name": "test_name",     "label": "Test / Examination", "field_type": "text"},
            {"name": "physician",     "label": "Physician",          "field_type": "text"},
            {"name": "facility",      "label": "Facility",           "field_type": "text"},
            {"name": "key_findings",  "label": "Key Findings",       "field_type": "text"},
            {"name": "summary",       "label": "Impression / Summary","field_type": "text"},
        ],
    },
    "bank_statement": {
        "label": "Bank Statement",
        "description": "Bank account statement",
        "fields": [
            {"name": "bank_name",         "label": "Bank Name",         "field_type": "text"},
            {"name": "account_holder",    "label": "Account Holder",    "field_type": "text"},
            {"name": "account_no",        "label": "Account Number",    "field_type": "text"},
            {"name": "statement_period",  "label": "Statement Period",  "field_type": "text"},
            {"name": "opening_balance",   "label": "Opening Balance",   "field_type": "currency"},
            {"name": "closing_balance",   "label": "Closing Balance",   "field_type": "currency"},
            {"name": "total_credits",     "label": "Total Credits",     "field_type": "currency"},
            {"name": "total_debits",      "label": "Total Debits",      "field_type": "currency"},
        ],
    },
    "id_card": {
        "label": "ID Card",
        "description": "Government-issued identity document",
        "fields": [
            {"name": "full_name",          "label": "Full Name",          "field_type": "text"},
            {"name": "dob",                "label": "Date of Birth",      "field_type": "date"},
            {"name": "id_number",          "label": "ID Number",          "field_type": "text"},
            {"name": "nationality",        "label": "Nationality",        "field_type": "text"},
            {"name": "issue_date",         "label": "Issue Date",         "field_type": "date"},
            {"name": "expiry_date",        "label": "Expiry Date",        "field_type": "date"},
            {"name": "issuing_authority",  "label": "Issuing Authority",  "field_type": "text"},
        ],
    },
    "purchase_order": {
        "label": "Purchase Order",
        "description": "Purchase order or procurement document",
        "fields": [
            {"name": "buyer",          "label": "Buyer",          "field_type": "text"},
            {"name": "supplier",       "label": "Supplier",       "field_type": "text"},
            {"name": "po_number",      "label": "PO Number",      "field_type": "text"},
            {"name": "date",           "label": "Order Date",     "field_type": "date"},
            {"name": "delivery_date",  "label": "Delivery Date",  "field_type": "date"},
            {"name": "items_summary",  "label": "Items Summary",  "field_type": "text"},
            {"name": "total",          "label": "Total Amount",   "field_type": "currency"},
            {"name": "terms",          "label": "Terms",          "field_type": "text"},
        ],
    },
}
